packages:
  - 'packages/*'

dangerouslyAllowAllBuilds: true

autoInstallPeers: true

minimumReleaseAgeExclude:
  - '@nx/devkit@22.7.5'
  - '@nx/js@22.7.5'
  - '@nx/nx-darwin-arm64@22.7.5'
  - '@nx/nx-darwin-x64@22.7.5'
  - '@nx/nx-freebsd-x64@22.7.5'
  - '@nx/nx-linux-arm-gnueabihf@22.7.5'
  - '@nx/nx-linux-arm64-gnu@22.7.5'
  - '@nx/nx-linux-arm64-musl@22.7.5'
  - '@nx/nx-linux-x64-gnu@22.7.5'
  - '@nx/nx-linux-x64-musl@22.7.5'
  - '@nx/nx-win32-arm64-msvc@22.7.5'
  - '@nx/nx-win32-x64-msvc@22.7.5'
  - '@nx/workspace@22.7.5'
  - nx@22.7.5
